### ISSUE TITLE
OrcaUI: pair along with FileManager API to able to browse runs output data

### ISSUE THREAD

**Issue by raylrui** [umccr/orca-ui#4]
OrcaUI pair along with FileManager API to able to browse runs output data

<img width="1082" alt="image" src="https://github.com/umccr/orca-ui/assets/160200168/26e5af3e-46ea-4bcd-bac5-cb4f59943e19">

Refer: https://umccr.slack.com/archives/C03ABJTSN7J/p1720521454971049

**Comment by williamputraintan** [comment]
Perhaps we proceed with this feature by adding a new section in `sideNavbar` and add either the 

Adding the FileTable viewer currently in place to have an unrestricted filter (currently it is available per `portalRunId`) 

OR

Explore if the aws-amplify-ui might be a good fit

`https://github.com/aws-amplify/amplify-ui/issues/5731`

**Comment by raylrui** [comment]
For the aws-amplify-ui https://github.com/aws-amplify/amplify-ui/issues/5731, Maybe we can check this one (for our ui consistency and reduce maintenance effort in the future)

<img width="855" alt="image" src="https://github.com/user-attachments/assets/3a2105bb-577d-4c80-b25c-e0658f5331e2">
