### ISSUE TITLE
reset paging parameters when filters are switched in Workflow view

### ISSUE THREAD

**Issue by reisingerf** [umccr/orca-ui#42]
In the Workflows view the paging parameters are kept in the URL when switching between different filters (succeeded, failed, etc). 

That leads to failures if there are not enough results to view.
Example:
- view all workflows
- navigate to a high page, e.g. page 10
- select a filter that has less result pages, e.g. `Failed`
- Error: `Unable to load workflow runs data`

**Comment by raylrui** [comment]
Good point, I just make a quick fix on that: https://github.com/umccr/orca-ui/pull/43

And I will make another issue on how our page handle api error from 'page or rowPerPage' out of range

**Comment by reisingerf** [comment]
Thanks!
