### ISSUE TITLE
WorkflowRun name is capitalised in view

### ISSUE THREAD

**Issue by reisingerf** [umccr/orca-ui#76]
When listing workflow runs, the workflow run name is capitalised in the view (the string is still correct / lowercase when copying though). 

See: https://orcaui.umccr.org/runs/workflow
Workflow run names look like `Umccr--Automated--...` compared to the original `umccr--automated--...`

**Comment by raylrui** [comment]
issue fixed with PR https://github.com/umccr/orca-ui/pull/73
now, the name will show same format as the database
<img width="570" alt="image" src="https://github.com/user-attachments/assets/dba9572c-2b38-4a14-a7df-1205865ba513">

**Comment by reisingerf** [comment]
I can see the change in the dev UI. 
Thanks!
