### ISSUE TITLE
Duplicate workflows when using workflow search

### ISSUE THREAD

**Issue by alexiswl** [umccr/orca-ui#82]
Steps to reproduce:

1. Head to orcaui workflow page
2. Search oncoanalyser-wgts-dna-rna

URL: https://orcaui.umccr.org/runs/workflow?search=oncoanalyser-wgts-dna-rna&page=1

![image](https://github.com/user-attachments/assets/c5029a2d-9248-4db4-87da-6e89349b5017)

**Comment by raylrui** [comment]
Fix and Analysis in PR: https://github.com/umccr/orcabus/pull/706

**Comment by raylrui** [comment]
resolve in DEV now: https://orcaui.dev.umccr.org/runs/workflow?search=oncoanalyser-wgts-dna
will close when new release to orcabus prod.

**Comment by raylrui** [comment]
Fixed in Prod: https://orcaui.umccr.org/runs/workflow?search=rnasum
